### ISSUE TITLE
Inconsistent Performance on builds which should be successful

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#236] opened 2022-08-01 18:58 UTC
Executed BUILD_ID of 1 and got a 50% Quality Gate score and a failing result when passing score is expected for demo purposes...

http://gitlab.acebox-kr.ace-innovation.info/demo/ace/-/pipelines/4

![image](https://user-images.githubusercontent.com/52331581/182223272-c4a3588d-f111-499f-a399-b4c3f6b7645e.png)

**Comment by kristofre** [comment] 2022-08-02 09:19
Thanks for flagging! Seems there is an issue within the tests where the api/invoke is struggling to make outbound calls related to resolving dns names. Might need some more investigation and caused by underlying kubernetes dns service.

**Comment by kristofre** [comment] 2022-08-02 09:20
Also seeing random failures like this in executions: 

```
fatal: unable to access 'http://gitlab.acebox-kr.ace-innovation.info/demo/ace.git/': Could not resolve host: gitlab.acebox-kr.ace-innovation.info 
```

**Comment by kristofre** [comment] 2022-08-02 09:29
Seeing lots of those on coredns logs:

```
[INFO] 10.1.210.98:37796 - 50208 "AAAA IN gitlab.acebox-kr.ace-innovation.info.google.internal. udp 70 false 512" NOERROR - 0 6.000875485s
[ERROR] plugin/errors: 2 gitlab.acebox-kr.ace-innovation.info.google.internal. AAAA: read udp 10.1.210.67:48648->8.8.8.8:53: i/o timeout
```

**Comment by kristofre** [comment] 2022-08-02 09:37
Plan is to change the sli to no longer look at the `/api/invoke` method for now, and in stead move to `/api/echo`. Both these methods are impacted by the same slow down but the `/api/echo` method is more consistent and not plagued by the DNS issues. DNS issues will need to be investigated separately.

update: no longer doing that, keeping original requests and fixing as described below

**Comment by kristofre** [comment] 2022-08-02 12:36
Update: for the jmeter-based tests (that jenkins employs), we send requests to `simplenode.NAMESPACE`, an internal endpoint to kubernetes.

the locust-based tests send the requests to the external url. This massive amount of requests is causing issues with name resolution. Easier fix would be to employ a local endpoint as well.

**Comment by kristofre** [comment] 2022-08-02 14:08
Update: There are also synthetic tests running against the staging environment, which are a lot slower than the locust based tests. This skews the data. 

Solution will be to update the calculated service metric to only calculate when the LSN/TSN/LTN request attributes are present.

In the future, we can update the quality gate definition to match also on the values of these request attributes (to distinguish individual runs)

**Closed as completed** 2022-08-03 06:01 UTC
Labels: bug
